// flow-typed signature: edd030596401ac046c29e4169af7b934
// flow-typed version: <<STUB>>/koa-bouncer_v5.1.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-bouncer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-bouncer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-bouncer/examples/basic' {
  declare module.exports: any;
}

declare module 'koa-bouncer/examples/full-example' {
  declare module.exports: any;
}

declare module 'koa-bouncer/sandbox/index' {
  declare module.exports: any;
}

declare module 'koa-bouncer/src/index' {
  declare module.exports: any;
}

declare module 'koa-bouncer/test' {
  declare module.exports: any;
}

declare module 'koa-bouncer/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-bouncer/examples/basic.js' {
  declare module.exports: $Exports<'koa-bouncer/examples/basic'>;
}
declare module 'koa-bouncer/examples/full-example.js' {
  declare module.exports: $Exports<'koa-bouncer/examples/full-example'>;
}
declare module 'koa-bouncer/sandbox/index.js' {
  declare module.exports: $Exports<'koa-bouncer/sandbox/index'>;
}
declare module 'koa-bouncer/src/index.js' {
  declare module.exports: $Exports<'koa-bouncer/src/index'>;
}
declare module 'koa-bouncer/test.js' {
  declare module.exports: $Exports<'koa-bouncer/test'>;
}
declare module 'koa-bouncer/test/index.test.js' {
  declare module.exports: $Exports<'koa-bouncer/test/index.test'>;
}
