// flow-typed signature: 6ca9e25abf80c5591c6dff647439747d
// flow-typed version: <<STUB>>/koa-helmet_v3.1.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-helmet/lib/index' {
  declare module.exports: any;
}

declare module 'koa-helmet/test/integration' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-helmet/lib/index.js' {
  declare module.exports: $Exports<'koa-helmet/lib/index'>;
}
declare module 'koa-helmet/test/integration.js' {
  declare module.exports: $Exports<'koa-helmet/test/integration'>;
}
