// flow-typed signature: 2f8fb2ea712720faee2397945b193996
// flow-typed version: <<STUB>>/passport-stub_v1.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-stub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-stub' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-stub/lib/passport-stub' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-stub/lib/passport-stub.js' {
  declare module.exports: $Exports<'passport-stub/lib/passport-stub'>;
}
