// flow-typed signature: a696de3c58bb33cd5bf71fece8d4f160
// flow-typed version: <<STUB>>/pg-extra_v0.0.13/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg-extra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg-extra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg-extra/src/index' {
  declare module.exports: any;
}

declare module 'pg-extra/src/SqlStatement' {
  declare module.exports: any;
}

declare module 'pg-extra/test/index.test' {
  declare module.exports: any;
}

declare module 'pg-extra/test/SqlStatement.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg-extra/src/index.js' {
  declare module.exports: $Exports<'pg-extra/src/index'>;
}
declare module 'pg-extra/src/SqlStatement.js' {
  declare module.exports: $Exports<'pg-extra/src/SqlStatement'>;
}
declare module 'pg-extra/test/index.test.js' {
  declare module.exports: $Exports<'pg-extra/test/index.test'>;
}
declare module 'pg-extra/test/SqlStatement.test.js' {
  declare module.exports: $Exports<'pg-extra/test/SqlStatement.test'>;
}
