// flow-typed signature: f274c6f329f11d0d47e70f3218861dca
// flow-typed version: <<STUB>>/supertest-koa-agent_v0.3.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'supertest-koa-agent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'supertest-koa-agent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'supertest-koa-agent/index' {
  declare module.exports: $Exports<'supertest-koa-agent'>;
}
declare module 'supertest-koa-agent/index.js' {
  declare module.exports: $Exports<'supertest-koa-agent'>;
}
